apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: rgw-tls
  namespace: ambassador
spec:
  hosts:
  - s3.analogsea.ca
  secret: rgw-cert
  # ambassador_id: ambassador-https
  redirect_cleartext_from: 8080
