apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-service-prod
  namespace: ambassador
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8089
  selector:
    certmanager.k8s.io/acme-http01-solver: "true"
    env: "prod"
