apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-restful
  namespace: rook-ceph
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
spec:
  type: ClusterIP
  ports:
  - name: restful
    port: 80
    protocol: TCP
    targetPort: 8003
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
