apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: rgw-external
  namespace: rook-ceph
spec:
  prefix: /
  # host: "ceph\\..*"
  host: s3.analogsea.ca
  host_regex: true
  service: rook-ceph-rgw-object-store.rook-ceph:80
  ambassador_id: ambassador-https
