apiVersion: v1
kind: Pod
metadata:
  name: centos-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: weave-test
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - clement-kube-node-2
  containers:
  - name: centos-pod-1
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
