apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    bluestore default buffered read = true
    osd_pool_default_size = 128
    perf = True
    rocksdb perf = True
    throttler perf counter = False

    [osd]
    osd_memory_target = 6000000000
    bluestore_csum_type = xxhash64
    bluestore_rocksdb_options = compression=kNoCompression,max_write_buffer_number=64,min_write_buffer_number_to_merge=32,recycle_log_file_num=64,compaction_style=kCompactionStyleLevel,write_buffer_size=4MB,target_file_size_base=4MB,max_background_compactions=64,level0_file_num_compaction_trigger=64,level0_slowdown_writes_trigger=128,level0_stop_writes_trigger=256,max_bytes_for_level_base=6GB,compaction_threads=32,flusher_threads=8,compaction_readahead_size=2MB

    bluestore_extent_map_shard_min_size = 50
    bluestore_extent_map_shard_max_size = 200
    bluestore_extent_map_shard_target_size = 100
    osd_min_pg_log_entries = 10
    osd_max_pg_log_entries = 10
    osd_pg_log_dups_tracked = 10
    osd_pg_log_trim_min = 10


    [client]
    rbd readahead disable after bytes = 0
    rbd readahead max bytes = 4194304
    rbd_cache = False
    rbd_cache_writethrough_until_flush = False
