apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: jenkins-tls
  namespace: ambassador
spec:
  hosts:
  - jenkins.analogsea.ca
  secret: jenkins-cert
  # ambassador_id: ambassador-https
  redirect_cleartext_from: 8080
