apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-service-dev
  namespace: ambassador
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
    env: "dev"
