apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: test
  namespace: default
spec:
  source:
    pvc:
      namespace: default
      name: ubuntu1604-file-template
  pvc:
    storageClassName: rook-ceph-block
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
