apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu-16.04-disk-3
spec:
  source:
    pvc:
      namespace: default
      name: ubuntu1604-template
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
