apiVersion: batch/v1
kind: Job
metadata:
  name: dbench
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: iexalt/fbench:1.0.0
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          - name: RAMP_TIME
            value: 10s
          - name: RUNTIME
            value: 10s
          - name: FIO_DIRECT
            value: "1"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: pvc-rbd
  backoffLimit: 4
