apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rbd
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  # volumeMode: Block
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
