apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-ceph-fs
  resources:
    requests:
      storage: 5Gi
