apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu-1604-block
  namespace: default
spec:
  source:
    pvc:
      namespace: default
      name: ubuntu1604-block-template
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
