apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu1604-block-template
  namespace: default
spec:
  source:
    registry:
      url: "docker://camelcasenotation/ubuntu1604-containerdisk"
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
